apiVersion: v1
kind: Namespace
metadata:
  name: iperf3
  labels:
   name: iperf3
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf3
  namespace: iperf3
  labels:
    k8s-app: iperf3
spec:
  selector:
    matchLabels:
      name: iperf3
  template:
    metadata:
      labels:
        name: iperf3
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: iperf3
        image: acloudiator/iperf3:latest
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
      terminationGracePeriodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: iperf3
  namespace: iperf3
spec:
  selector:
    app: iperf3
  ports:
  - protocol: TCP
    port: 5201
    targetPort: 5201
